spring.application.name=damn-vuln-app

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:vulndb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

# ? THIS is the fix ? tells Spring to wait for Hibernate to create
#   the tables FIRST, then run data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

server.port=8085